# Generated by Django 4.1.6 on 2023-02-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="author",),
        migrations.RemoveField(model_name="comment", name="post",),
        migrations.RemoveField(model_name="post", name="author",),
        migrations.RemoveField(model_name="post", name="category",),
        migrations.RemoveField(model_name="post", name="file_upload",),
        migrations.RemoveField(model_name="post", name="head_image",),
        migrations.RemoveField(model_name="post", name="hook_text",),
        migrations.RemoveField(model_name="post", name="tags",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Comment",),
        migrations.DeleteModel(name="Tag",),
    ]
