# Generated by Django 4.1.6 on 2023-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_comment_author_remove_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=models.TextField(),
        ),
    ]
