# Generated by Django 4.1.6 on 2023-02-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_author_post_file_upload_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "categories"},
        ),
    ]
